using PInvoke;
/// <summary>
/// This file supplements code generated by CsWin32
/// </summary>
namespace Windows.Win32.Foundation;

readonly partial struct NTSTATUS
{
    public bool IsSuccessful => SeverityCode is Severity.Success;

    /// <inheritdoc cref="Kernel32Extensions.ThrowOnError(PInvoke.NTSTATUS)"/>
    public void ThrowOnError()
    {
        if (SeverityCode == Severity.Error)
            throw new NTStatusException(this);
    }

    /// <inheritdoc cref="Kernel32Extensions.GetMessage(global::PInvoke.NTSTATUS)"/>
    public string GetMessage() => ((global::PInvoke.NTSTATUS)this).GetMessage();

    public static implicit operator global::PInvoke.NTSTATUS(NTSTATUS v) => new(v.Value);
    public static implicit operator NTSTATUS(global::PInvoke.NTSTATUS v) => new(v.AsInt32);

    public static implicit operator global::PInvoke.NTSTATUS.Code(NTSTATUS v) => ((global::PInvoke.NTSTATUS)v).Value;
}
