/// This file supplements code generated by CsWin32
using NTStatusException = PInvoke.NTStatusException;

namespace Windows.Win32.Foundation;

readonly partial struct NTSTATUS
{
    public bool IsSuccessful => SeverityCode == Severity.Success;

    public NTStatusException GetNTStatusException() => new(this);

    public static implicit operator global::PInvoke.NTSTATUS(NTSTATUS v) => new(v.Value);
    public static implicit operator NTSTATUS(global::PInvoke.NTSTATUS v) => new(v.AsInt32);

    public static implicit operator global::PInvoke.NTSTATUS.Code(NTSTATUS v) => ((global::PInvoke.NTSTATUS)v).Value;
}
